// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/ehazlett/blackbird/api/v1/proxy.proto

package api // import "github.com/ehazlett/blackbird/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Policy int32

const (
	Policy_RANDOM      Policy = 0
	Policy_LEAST_CONN  Policy = 1
	Policy_ROUND_ROBIN Policy = 2
	Policy_FIRST       Policy = 3
	Policy_IP_HASH     Policy = 4
	Policy_URI_HASH    Policy = 5
	Policy_HEADER      Policy = 6
)

var Policy_name = map[int32]string{
	0: "RANDOM",
	1: "LEAST_CONN",
	2: "ROUND_ROBIN",
	3: "FIRST",
	4: "IP_HASH",
	5: "URI_HASH",
	6: "HEADER",
}
var Policy_value = map[string]int32{
	"RANDOM":      0,
	"LEAST_CONN":  1,
	"ROUND_ROBIN": 2,
	"FIRST":       3,
	"IP_HASH":     4,
	"URI_HASH":    5,
	"HEADER":      6,
}

func (x Policy) String() string {
	return proto.EnumName(Policy_name, int32(x))
}
func (Policy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{0}
}

type HealthCheck struct {
	HealthCheck          string          `protobuf:"bytes,1,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	HealthCheckInterval  *types.Duration `protobuf:"bytes,2,opt,name=health_check_interval,json=healthCheckInterval" json:"health_check_interval,omitempty"`
	HealthCheckTimeout   *types.Duration `protobuf:"bytes,3,opt,name=health_check_timeout,json=healthCheckTimeout" json:"health_check_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{0}
}
func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (dst *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(dst, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetHealthCheck() string {
	if m != nil {
		return m.HealthCheck
	}
	return ""
}

func (m *HealthCheck) GetHealthCheckInterval() *types.Duration {
	if m != nil {
		return m.HealthCheckInterval
	}
	return nil
}

func (m *HealthCheck) GetHealthCheckTimeout() *types.Duration {
	if m != nil {
		return m.HealthCheckTimeout
	}
	return nil
}

type Server struct {
	Host                 string       `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path                 string       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TLS                  bool         `protobuf:"varint,3,opt,name=tls,proto3" json:"tls,omitempty"`
	Policy               Policy       `protobuf:"varint,4,opt,name=policy,proto3,enum=blackbird.api.v1.Policy" json:"policy,omitempty"`
	Backends             []string     `protobuf:"bytes,5,rep,name=backends" json:"backends,omitempty"`
	HealthCheck          *HealthCheck `protobuf:"bytes,6,opt,name=health_check,json=healthCheck" json:"health_check,omitempty"`
	InsecureSkipVerify   bool         `protobuf:"varint,7,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	Preset               string       `protobuf:"bytes,8,opt,name=preset,proto3" json:"preset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{1}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (dst *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(dst, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Server) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Server) GetTLS() bool {
	if m != nil {
		return m.TLS
	}
	return false
}

func (m *Server) GetPolicy() Policy {
	if m != nil {
		return m.Policy
	}
	return Policy_RANDOM
}

func (m *Server) GetBackends() []string {
	if m != nil {
		return m.Backends
	}
	return nil
}

func (m *Server) GetHealthCheck() *HealthCheck {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

func (m *Server) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Server) GetPreset() string {
	if m != nil {
		return m.Preset
	}
	return ""
}

type AddServerRequest struct {
	Server               *Server  `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddServerRequest) Reset()         { *m = AddServerRequest{} }
func (m *AddServerRequest) String() string { return proto.CompactTextString(m) }
func (*AddServerRequest) ProtoMessage()    {}
func (*AddServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{2}
}
func (m *AddServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddServerRequest.Unmarshal(m, b)
}
func (m *AddServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddServerRequest.Marshal(b, m, deterministic)
}
func (dst *AddServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddServerRequest.Merge(dst, src)
}
func (m *AddServerRequest) XXX_Size() int {
	return xxx_messageInfo_AddServerRequest.Size(m)
}
func (m *AddServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddServerRequest proto.InternalMessageInfo

func (m *AddServerRequest) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

type RemoveServerRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveServerRequest) Reset()         { *m = RemoveServerRequest{} }
func (m *RemoveServerRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveServerRequest) ProtoMessage()    {}
func (*RemoveServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{3}
}
func (m *RemoveServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveServerRequest.Unmarshal(m, b)
}
func (m *RemoveServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveServerRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveServerRequest.Merge(dst, src)
}
func (m *RemoveServerRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveServerRequest.Size(m)
}
func (m *RemoveServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveServerRequest proto.InternalMessageInfo

func (m *RemoveServerRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type ReloadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadRequest) Reset()         { *m = ReloadRequest{} }
func (m *ReloadRequest) String() string { return proto.CompactTextString(m) }
func (*ReloadRequest) ProtoMessage()    {}
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{4}
}
func (m *ReloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadRequest.Unmarshal(m, b)
}
func (m *ReloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadRequest.Marshal(b, m, deterministic)
}
func (dst *ReloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadRequest.Merge(dst, src)
}
func (m *ReloadRequest) XXX_Size() int {
	return xxx_messageInfo_ReloadRequest.Size(m)
}
func (m *ReloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadRequest proto.InternalMessageInfo

type ServersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServersRequest) Reset()         { *m = ServersRequest{} }
func (m *ServersRequest) String() string { return proto.CompactTextString(m) }
func (*ServersRequest) ProtoMessage()    {}
func (*ServersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{5}
}
func (m *ServersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServersRequest.Unmarshal(m, b)
}
func (m *ServersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServersRequest.Marshal(b, m, deterministic)
}
func (dst *ServersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServersRequest.Merge(dst, src)
}
func (m *ServersRequest) XXX_Size() int {
	return xxx_messageInfo_ServersRequest.Size(m)
}
func (m *ServersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServersRequest proto.InternalMessageInfo

type ServersResponse struct {
	Servers              []*Server `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServersResponse) Reset()         { *m = ServersResponse{} }
func (m *ServersResponse) String() string { return proto.CompactTextString(m) }
func (*ServersResponse) ProtoMessage()    {}
func (*ServersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_proxy_4dadbf585e7dd3bf, []int{6}
}
func (m *ServersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServersResponse.Unmarshal(m, b)
}
func (m *ServersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServersResponse.Marshal(b, m, deterministic)
}
func (dst *ServersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServersResponse.Merge(dst, src)
}
func (m *ServersResponse) XXX_Size() int {
	return xxx_messageInfo_ServersResponse.Size(m)
}
func (m *ServersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServersResponse proto.InternalMessageInfo

func (m *ServersResponse) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthCheck)(nil), "blackbird.api.v1.HealthCheck")
	proto.RegisterType((*Server)(nil), "blackbird.api.v1.Server")
	proto.RegisterType((*AddServerRequest)(nil), "blackbird.api.v1.AddServerRequest")
	proto.RegisterType((*RemoveServerRequest)(nil), "blackbird.api.v1.RemoveServerRequest")
	proto.RegisterType((*ReloadRequest)(nil), "blackbird.api.v1.ReloadRequest")
	proto.RegisterType((*ServersRequest)(nil), "blackbird.api.v1.ServersRequest")
	proto.RegisterType((*ServersResponse)(nil), "blackbird.api.v1.ServersResponse")
	proto.RegisterEnum("blackbird.api.v1.Policy", Policy_name, Policy_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	AddServer(ctx context.Context, in *AddServerRequest, opts ...grpc.CallOption) (*types.Empty, error)
	RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Servers(ctx context.Context, in *ServersRequest, opts ...grpc.CallOption) (*ServersResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type proxyClient struct {
	cc *grpc.ClientConn
}

func NewProxyClient(cc *grpc.ClientConn) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) AddServer(ctx context.Context, in *AddServerRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/blackbird.api.v1.Proxy/AddServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) RemoveServer(ctx context.Context, in *RemoveServerRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/blackbird.api.v1.Proxy/RemoveServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Servers(ctx context.Context, in *ServersRequest, opts ...grpc.CallOption) (*ServersResponse, error) {
	out := new(ServersResponse)
	err := c.cc.Invoke(ctx, "/blackbird.api.v1.Proxy/Servers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/blackbird.api.v1.Proxy/Reload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServer is the server API for Proxy service.
type ProxyServer interface {
	AddServer(context.Context, *AddServerRequest) (*types.Empty, error)
	RemoveServer(context.Context, *RemoveServerRequest) (*types.Empty, error)
	Servers(context.Context, *ServersRequest) (*ServersResponse, error)
	Reload(context.Context, *ReloadRequest) (*types.Empty, error)
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_AddServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).AddServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blackbird.api.v1.Proxy/AddServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).AddServer(ctx, req.(*AddServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_RemoveServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).RemoveServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blackbird.api.v1.Proxy/RemoveServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).RemoveServer(ctx, req.(*RemoveServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Servers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Servers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blackbird.api.v1.Proxy/Servers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Servers(ctx, req.(*ServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blackbird.api.v1.Proxy/Reload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blackbird.api.v1.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddServer",
			Handler:    _Proxy_AddServer_Handler,
		},
		{
			MethodName: "RemoveServer",
			Handler:    _Proxy_RemoveServer_Handler,
		},
		{
			MethodName: "Servers",
			Handler:    _Proxy_Servers_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _Proxy_Reload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ehazlett/blackbird/api/v1/proxy.proto",
}

func init() {
	proto.RegisterFile("github.com/ehazlett/blackbird/api/v1/proxy.proto", fileDescriptor_proxy_4dadbf585e7dd3bf)
}

var fileDescriptor_proxy_4dadbf585e7dd3bf = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xda, 0x5c,
	0x10, 0xfd, 0x0c, 0xc1, 0xc0, 0x90, 0x2f, 0xb1, 0x26, 0x69, 0xe4, 0x50, 0xb5, 0x21, 0x96, 0x2a,
	0xd1, 0x2c, 0xec, 0x84, 0x2e, 0xbb, 0x29, 0x09, 0xb4, 0xa0, 0x26, 0x10, 0x5d, 0x48, 0x17, 0xdd,
	0x58, 0xc6, 0xdc, 0x60, 0x0b, 0xc3, 0x75, 0xed, 0x0b, 0x6a, 0xfa, 0x3e, 0x7d, 0x81, 0x3e, 0x47,
	0x9f, 0xa1, 0x8b, 0x3e, 0x49, 0xe5, 0x6b, 0x83, 0x1c, 0x7e, 0xd2, 0xee, 0xee, 0xcc, 0x39, 0x73,
	0x66, 0xe6, 0x0c, 0x06, 0xce, 0x47, 0x2e, 0x77, 0x66, 0x03, 0xdd, 0x66, 0x13, 0x83, 0x3a, 0xd6,
	0x37, 0x8f, 0x72, 0x6e, 0x0c, 0x3c, 0xcb, 0x1e, 0x0f, 0xdc, 0x60, 0x68, 0x58, 0xbe, 0x6b, 0xcc,
	0x2f, 0x0c, 0x3f, 0x60, 0x5f, 0x1f, 0x74, 0x3f, 0x60, 0x9c, 0xa1, 0xb2, 0x44, 0x75, 0xcb, 0x77,
	0xf5, 0xf9, 0x45, 0xf9, 0x70, 0xc4, 0x46, 0x4c, 0x80, 0x46, 0xf4, 0x8a, 0x79, 0xe5, 0xe7, 0x23,
	0xc6, 0x46, 0x1e, 0x35, 0x44, 0x34, 0x98, 0xdd, 0x1b, 0x74, 0xe2, 0xf3, 0x44, 0xa4, 0xfc, 0x72,
	0x15, 0x1c, 0xce, 0x02, 0x8b, 0xbb, 0x6c, 0x1a, 0xe3, 0xda, 0x4f, 0x09, 0x4a, 0x2d, 0x6a, 0x79,
	0xdc, 0xb9, 0x72, 0xa8, 0x3d, 0xc6, 0x53, 0xd8, 0x75, 0x44, 0x68, 0xda, 0x51, 0xac, 0x4a, 0x15,
	0xa9, 0x5a, 0x24, 0x25, 0x27, 0x45, 0xb9, 0x81, 0x67, 0x69, 0x8a, 0xe9, 0x4e, 0x39, 0x0d, 0xe6,
	0x96, 0xa7, 0x66, 0x2a, 0x52, 0xb5, 0x54, 0x3b, 0xd6, 0xe3, 0x96, 0xfa, 0xa2, 0xa5, 0xde, 0x48,
	0x5a, 0x92, 0x83, 0x94, 0x4c, 0x3b, 0xa9, 0xc2, 0x8f, 0x70, 0xf8, 0x48, 0x8e, 0xbb, 0x13, 0xca,
	0x66, 0x5c, 0xcd, 0xfe, 0x4d, 0x0d, 0x53, 0x6a, 0xfd, 0xb8, 0x48, 0xfb, 0x9e, 0x01, 0xb9, 0x47,
	0x83, 0x39, 0x0d, 0x10, 0x61, 0xc7, 0x61, 0x21, 0x4f, 0x36, 0x10, 0xef, 0x28, 0xe7, 0x5b, 0xdc,
	0x11, 0x93, 0x16, 0x89, 0x78, 0xe3, 0x31, 0x64, 0xb9, 0x17, 0x8a, 0x76, 0x85, 0xcb, 0xfc, 0xef,
	0x5f, 0x27, 0xd9, 0xfe, 0x75, 0x8f, 0x44, 0x39, 0x3c, 0x07, 0xd9, 0x67, 0x9e, 0x6b, 0x3f, 0xa8,
	0x3b, 0x15, 0xa9, 0xba, 0x57, 0x53, 0xf5, 0xd5, 0x93, 0xe8, 0xb7, 0x02, 0x27, 0x09, 0x0f, 0xcb,
	0x50, 0x18, 0x58, 0xf6, 0x98, 0x4e, 0x87, 0xa1, 0x9a, 0xab, 0x64, 0xab, 0x45, 0xb2, 0x8c, 0xf1,
	0xdd, 0x8a, 0xb5, 0xb2, 0x58, 0xf0, 0xc5, 0xba, 0x66, 0xea, 0x1e, 0x8f, 0x9d, 0x3f, 0x87, 0x43,
	0x77, 0x1a, 0x52, 0x7b, 0x16, 0x50, 0x33, 0x1c, 0xbb, 0xbe, 0x39, 0xa7, 0x81, 0x7b, 0xff, 0xa0,
	0xe6, 0xa3, 0xd9, 0x09, 0x2e, 0xb0, 0xde, 0xd8, 0xf5, 0x3f, 0x09, 0x04, 0x8f, 0x40, 0xf6, 0x03,
	0x1a, 0x52, 0xae, 0x16, 0xc4, 0xca, 0x49, 0xa4, 0x35, 0x40, 0xa9, 0x0f, 0x87, 0xb1, 0x53, 0x84,
	0x7e, 0x99, 0xd1, 0x90, 0x47, 0xdb, 0x86, 0x22, 0x21, 0x2c, 0x2b, 0x6d, 0xda, 0x36, 0x29, 0x48,
	0x78, 0xda, 0x6b, 0x38, 0x20, 0x74, 0xc2, 0xe6, 0xf4, 0xb1, 0xd0, 0x06, 0xe7, 0xb5, 0x7d, 0xf8,
	0x9f, 0x50, 0x8f, 0x59, 0xc3, 0x84, 0xa4, 0x29, 0xb0, 0x17, 0x57, 0x85, 0x8b, 0x4c, 0x13, 0xf6,
	0x97, 0x99, 0xd0, 0x67, 0xd3, 0x90, 0x62, 0x0d, 0xf2, 0x71, 0xab, 0x50, 0x95, 0x2a, 0xd9, 0x27,
	0x67, 0x5a, 0x10, 0xcf, 0x46, 0x20, 0xc7, 0x47, 0x41, 0x00, 0x99, 0xd4, 0x3b, 0x8d, 0xee, 0x8d,
	0xf2, 0x1f, 0xee, 0x01, 0x5c, 0x37, 0xeb, 0xbd, 0xbe, 0x79, 0xd5, 0xed, 0x74, 0x14, 0x09, 0xf7,
	0xa1, 0x44, 0xba, 0x77, 0x9d, 0x86, 0x49, 0xba, 0x97, 0xed, 0x8e, 0x92, 0xc1, 0x22, 0xe4, 0xde,
	0xb7, 0x49, 0xaf, 0xaf, 0x64, 0xb1, 0x04, 0xf9, 0xf6, 0xad, 0xd9, 0xaa, 0xf7, 0x5a, 0xca, 0x0e,
	0xee, 0x42, 0xe1, 0x8e, 0xb4, 0xe3, 0x28, 0x17, 0x49, 0xb6, 0x9a, 0xf5, 0x46, 0x93, 0x28, 0x72,
	0xed, 0x47, 0x06, 0x72, 0xb7, 0xd1, 0xf7, 0x8a, 0x1f, 0xa0, 0xb8, 0x74, 0x13, 0xb5, 0xf5, 0x11,
	0x57, 0xad, 0x2e, 0x1f, 0xad, 0xfd, 0xaa, 0x9b, 0xd1, 0x37, 0x8b, 0x37, 0xb0, 0x9b, 0x36, 0x14,
	0x5f, 0xad, 0x6b, 0x6d, 0x30, 0x7c, 0xab, 0x5c, 0x07, 0xf2, 0x89, 0xa3, 0x58, 0xd9, 0x66, 0xdc,
	0xc2, 0xfe, 0xf2, 0xe9, 0x13, 0x8c, 0xe4, 0x1c, 0x75, 0x90, 0xe3, 0x23, 0xe2, 0xc9, 0xa6, 0xc1,
	0x52, 0xe7, 0xdd, 0x36, 0xd2, 0xe5, 0xd9, 0xe7, 0xea, 0xbf, 0xfc, 0x11, 0xbe, 0xb5, 0x7c, 0x77,
	0x20, 0x8b, 0xda, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x09, 0x94, 0x91, 0x3b, 0x05,
	0x00, 0x00,
}
